import { NextRequest, NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/whatsapp/flows/admin-client'
import { decrypt } from '@/lib/whatsapp/whatsapp/encryption'
import { sendTemplateMessage } from '@/lib/whatsapp/whatsapp/meta-api'
import { verifySupabaseHookSignature } from '@/lib/whatsapp/supabase-hooks/verify-signature'

// Supabase Auth's "Send SMS Hook" — called instead of a built-in SMS
// provider (Twilio/etc) whenever a phone OTP needs to be sent. We deliver
// it as a WhatsApp message through the same Meta WhatsApp Business number
// already configured for the comm center (`whatsapp_config`), reusing
// Kiranam's existing infrastructure instead of paying for a second
// number/provider.
//
// Configure in Supabase Dashboard → Auth → Hooks → Send SMS hook:
//   URL: https://<this-wacrm-deployment>/api/auth-hooks/send-sms
//   Secret: generated by Supabase, paste into this app's SEND_SMS_HOOK_SECRET.
//
// Prerequisites this route depends on (see WHATSAPP.md):
//   1. A WhatsApp Business number connected in wacrm Settings for the
//      Kiranam account (populates `whatsapp_config`).
//   2. A Meta-approved AUTHENTICATION-category template (must be created
//      directly in Meta WhatsApp Manager — wacrm's own template UI
//      deliberately rejects creating Authentication templates; use
//      "Sync from Meta" afterward, or just reference it by name here).
//      Template name/language: OTP_TEMPLATE_NAME / OTP_TEMPLATE_LANGUAGE.
interface SendSmsHookPayload {
  user: { phone?: string }
  sms: { otp: string }
}

export async function POST(request: NextRequest) {
  const rawBody = await request.text()

  const verified = verifySupabaseHookSignature(rawBody, {
    id: request.headers.get('webhook-id'),
    timestamp: request.headers.get('webhook-timestamp'),
    signature: request.headers.get('webhook-signature'),
  })
  if (!verified) {
    return NextResponse.json({ error: 'invalid signature' }, { status: 401 })
  }

  let payload: SendSmsHookPayload
  try {
    payload = JSON.parse(rawBody)
  } catch {
    return NextResponse.json({ error: 'invalid body' }, { status: 400 })
  }

  const phone = payload.user?.phone
  const otp = payload.sms?.otp
  if (!phone || !otp) {
    return NextResponse.json({ error: 'missing phone or otp' }, { status: 400 })
  }

  // Extra layer of control on top of whatever Supabase's own platform OTP
  // rate limits already do — this one we can see and tune ourselves, and it
  // caps the real cost driver here (a WhatsApp template send per OTP).
  const { data: limitCheck } = await supabaseAdmin()
    .rpc('check_and_record_rate_limit', {
      p_key: `otp_send:${phone.replace(/\D/g, '')}`,
      p_limit: 5,
      p_window_seconds: 60 * 60,
      p_lockout_seconds: 60 * 60,
    })
    .single<{ allowed: boolean; retry_after_seconds: number }>()
  if (limitCheck && !limitCheck.allowed) {
    console.warn('[send-sms-hook] rate limited', phone, 'retry after', limitCheck.retry_after_seconds)
    return NextResponse.json({ error: 'rate_limited' }, { status: 429 })
  }

  const accountId = process.env.KIRANAM_WACRM_ACCOUNT_ID
  const templateName = process.env.OTP_TEMPLATE_NAME
  if (!accountId || !templateName) {
    console.error('[send-sms-hook] KIRANAM_WACRM_ACCOUNT_ID / OTP_TEMPLATE_NAME not configured')
    return NextResponse.json({ error: 'not_configured' }, { status: 500 })
  }

  const { data: config, error: configError } = await supabaseAdmin()
    .from('whatsapp_config')
    .select('phone_number_id, access_token, status')
    .eq('account_id', accountId)
    .single()

  if (configError || !config || config.status !== 'connected') {
    console.error('[send-sms-hook] no connected whatsapp_config for account', accountId, configError)
    return NextResponse.json({ error: 'whatsapp_not_connected' }, { status: 500 })
  }

  try {
    await sendTemplateMessage({
      phoneNumberId: config.phone_number_id,
      accessToken: decrypt(config.access_token),
      to: phone.replace(/\D/g, ''),
      templateName,
      language: process.env.OTP_TEMPLATE_LANGUAGE || 'en_US',
      params: [otp],
    })
  } catch (err) {
    console.error('[send-sms-hook] failed to send OTP via WhatsApp', err)
    return NextResponse.json({ error: 'send_failed' }, { status: 502 })
  }

  return NextResponse.json({})
}
